--- #YAML:1.0
name:                Shell-Perl
version:             0.0016
abstract:            A read-eval-print loop in Perl 
license:             perl
author:              
    - A. R. Ferreira <ferreira@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor:               0
    File::Basename:                0
    File::HomeDir:                 0
    File::Slurp:                   0
    Getopt::Long:                  0
    Path::Class:                   0
    Term::ReadLine:                0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
